
server:
  port: 8080

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 2
    instances:
      serviceA:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
  retry:
    retryAspectOrder: 5
    instances:
      serviceA:
        maxAttempts: 5
        waitDuration : 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        #retry-exceptions:
        #  - org.springframework.web.client.RestClientException
        #ignore-exceptions:


#  ratelimiter:
#    instances:
#      serviceA:
#        registerHealthIndicator: false
#        limitForPeriod: 10
#        limitRefreshPeriod: 10s
#        timeoutDuration: 3s






